SET NAMES 'latin1';
DROP DATABASE IF EXISTS SITarea1;
CREATE DATABASE IF NOT EXISTS SITarea1 DEFAULT CHARACTER SET utf8;
USE SITarea1;

CREATE TABLE nombres(
id_nbs INTEGER NOT NULL AUTO_INCREMENT,
nombre_nbs VARCHAR(100) NOT NULL,
PRIMARY KEY (id_nbs)
)DEFAULT CHARACTER SET utf8;